#
FROM python:3.11

#
WORKDIR /Auth-Server

#
COPY ./requirements.txt /Auth-Server/requirements.txt

#
RUN pip install --no-cache-dir --upgrade -r /Auth-Server/requirements.txt

#
COPY ./app /Auth-Server/app

#
COPY ./.env /Auth-Server/.env

#
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]